## Simulations for the Bragg grating, in Lumerical FDTD Solutions (3D Simulation);
# script file: Bragg_FDTD.lsf
#Create and simulate a basic Bragg grating which are being studied by the B.Tech ECE students.
#Copyright 2014 Lumerical Solutions
###############################

DESIGN PARAMETERS
###############################
thick_Si = 0.22e-6;
thick_BOX = 2e-6;
Width_ridge = 0.56e-6; # Waveguide Width
